url: "https://adrius.blog"
baseurl: ""
title: "adrius"
lang: fr-FR
description: "Projets, notes et idées d'adrius."
author:
  name: adrius
keywords: [code, craft, projets, notes, idées, blog, codeur, développement, design]

collections:
  posts:
    output: true
    permalink: /posts/:slug/

include: ["_pages"]

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      body_class: page-blog-single
  - scope:
      path: "_pages"
    values:
      layout: default

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: false

plugins: [jekyll-feed, jekyll-seo-tag]
exclude: [Gemfile, Gemfile.lock, vendor, public, themes, node_modules, layouts, hugo.toml, content, cloudgoat, archetypes, data, static]
